import Head from "next/head";
import axios from 'axios';
import { useEffect, useState } from "react";
import Image from "next/image";
import { BsSearch } from 'react-icons/bs';
import Spinner from "../components/Spinner";
import Weather from "../components/Weather";

export default function Home() {
  const [city, setCity] = useState('');
  const [weather, setWeather] = useState({});
  const [error, setError] = useState(false);
  const [loading, setLoading] = useState(false);


  const url = `https://api.openweathermap.org/data/2.5/weather?q=${city}&appid=${process.env.NEXT_PUBLIC_WEATHER_API}`;

  const fetchWeather = async (e) => {
    console.log("inside search weather..........");
    e.preventDefault();
    setLoading(true);
    setError(false);
    try {
      console.log(url);
      const response = await axios.get(url);
      setWeather(response.data);
      setLoading(false);
      setCity('');
    } catch (error) {
      console.error(error);
      setError(true);
      setLoading(false);
    }
  };

  if (loading) {
    return <Spinner />;
  } else {
    return (
      <div className="relative w-full h-screen overflow-hidden">
        <Head>
          <title>Weather - App</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        {/* overlay */}
        <div className="absolute inset-0 bg-black/40 z-[1]" />

        {/* background */}
        <Image
          src={'https://images.unsplash.com/photo-1601134467661-3d775b999c8b?q=80&w=1375&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D'}
          fill
          style={{ objectFit: "cover" }}
          className="object-cover"
          alt="Weather App Background image"
        />

        {/* SEARCH */}
        <div className='relative flex justify-between items-center max-w-[500px] w-full m-auto pt-4 px-4 text-white z-10'>
          <form
            onSubmit={fetchWeather}
            className='flex justify-between items-center w-full m-auto p-3 bg-transparent border-2 border-gray-300 text-white rounded-2xl'
          >
            <div>
              <input
                type="text"
                value={city}
                onChange={(e) => {
                  e.preventDefault();
                  setCity(e.target.value)
                }}
                placeholder="Enter city"
                className="bg-transparent border-none w-[80%] text-white focus:outline-none text-2xl placeholder:text-white"
              />
            </div>
            <button type="submit" className="p-2"><BsSearch size={20} /></button>
          </form>
        </div>
        {/* Weather */}
        {weather.main && <Weather data={weather} />}
      </div>
    );
  }
}
